x

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,7 +12,7 @@ jobs:
     - name: Install System Dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y libgmp-dev
+        sudo apt-get install -y libgmp-dev aspcud
 
     - uses: actions/checkout@v4
 
@@ -20,7 +20,7 @@ jobs:
       uses: actions/cache@v4
       with:
         path: ~/.opam
-        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}-v8 # Incremented to v8
+        key: ${{ runner.os }}-opam-${{ hashFiles('**/_CoqProject') }}-v9 # Incremented to v9
         restore-keys: |
           ${{ runner.os }}-opam-
 
@@ -83,14 +83,15 @@ jobs:
         set -exo pipefail
         echo "Pinning Coq 8.16.1 from Git..."
         touch pin_coq.log
-        opam pin add coq https://github.com/coq/coq.git#V8.16.1 -y --verbose --debug >> pin_coq.log 2>&1
-        if [ $? -ne 0 ]; then
-          echo "Pinning failed"
+        opam pin add coq https://github.com/coq/coq.git#V8.16.1 -y --verbose --debug --show > pin_coq.log 2>&1
+        PIN_EXIT_CODE=$?
+        stdbuf -oL tee -a pin_coq.log < pin_coq.log
+        if [ $PIN_EXIT_CODE -ne 0 ]; then
+          echo "Pinning failed with exit code $PIN_EXIT_CODE"
           cat pin_coq.log
           opam list --all-versions coq
           exit 1
         fi
-        stdbuf -oL tee -a pin_coq.log < pin_coq.log
         echo "Verifying pin_coq.log..."
         ls -l pin_coq.log
         cat pin_coq.log
@@ -110,14 +111,15 @@ jobs:
         touch install_coq.log
         opam install coq.8.16.1 --show-actions | stdbuf -oL tee -a install_coq.log
         echo "Installing Coq 8.16.1..."
-        opam install coq.8.16.1 -y --verbose --debug >> install_coq.log 2>&1
-        if [ $? -ne 0 ]; then
-          echo "Coq 8.16.1 installation failed"
+        opam install coq.8.16.1 -y --verbose --debug > install_coq.log 2>&1
+        INSTALL_EXIT_CODE=$?
+        stdbuf -oL tee -a install_coq.log < install_coq.log
+        if [ $INSTALL_EXIT_CODE -ne 0 ]; then
+          echo "Coq 8.16.1 installation failed with exit code $INSTALL_EXIT_CODE"
           cat install_coq.log
           opam list --all-versions coq
           exit 1
         fi
-        stdbuf -oL tee -a install_coq.log < install_coq.log
         echo "Verifying install_coq.log..."
         ls -l install_coq.log
         cat install_coq.log
@@ -149,14 +151,15 @@ jobs:
     #     set -exo pipefail
     #     echo "Pinning Coq 8.16.1..."
     #     touch pin_coq.log
-    #     opam pin add coq 8.16.1 -y --verbose --debug >> pin_coq.log 2>&1
-    #     if [ $? -ne 0 ]; then
-    #       echo "Pinning failed"
+    #     opam pin add coq 8.16.1 -y --verbose --debug --show > pin_coq.log 2>&1
+    #     PIN_EXIT_CODE=$?
+    #     stdbuf -oL tee -a pin_coq.log < pin_coq.log
+    #     if [ $PIN_EXIT_CODE -ne 0 ]; then
+    #       echo "Pinning failed with exit code $PIN_EXIT_CODE"
     #       cat pin_coq.log
     #       opam list --all-versions coq
     #       exit 1
     #     fi
-    #     stdbuf -oL tee -a pin_coq.log < pin_coq.log
     #     echo "Verifying pin_coq.log..."
     #     ls -l pin_coq.log
     #     cat pin_coq.log
@@ -176,14 +179,15 @@ jobs:
     #     touch install_coq.log
     #     opam install coq.8.16.1 --show-actions | stdbuf -oL tee -a install_coq.log
     #     echo "Installing Coq 8.16.1..."
-    #     opam install coq.8.16.1 -y --verbose --debug >> install_coq.log 2>&1
-    #     if [ $? -ne 0 ]; then
-    #       echo "Coq 8.16.1 installation failed"
+    #     opam install coq.8.16.1 -y --verbose --debug > install_coq.log 2>&1
+    #     INSTALL_EXIT_CODE=$?
+    #     stdbuf -oL tee -a install_coq.log < install_coq.log
+    #     if [ $INSTALL_EXIT_CODE -ne 0 ]; then
+    #       echo "Coq 8.16.1 installation failed with exit code $INSTALL_EXIT_CODE"
     #       cat install_coq.log
     #       opam list --all-versions coq
     #       exit 1
     #     fi
-    #     stdbuf -oL tee -a install_coq.log < install_coq.log
     #     echo "Verifying install_coq.log..."
     #     ls -l install_coq.log
     #     cat install_coq.log
@@ -216,14 +220,15 @@ jobs:
     #     set -exo pipefail
     #     echo "Pinning Rocq 9.0.0..."
     #     touch pin_coq.log
-    #     opam pin add coq 9.0.0 -y --verbose --debug >> pin_coq.log 2>&1
-    #     if [ $? -ne 0 ]; then
-    #       echo "Pinning failed"
+    #     opam pin add coq 9.0.0 -y --verbose --debug --show > pin_coq.log 2>&1
+    #     PIN_EXIT_CODE=$?
+    #     stdbuf -oL tee -a pin_coq.log < pin_coq.log
+    #     if [ $PIN_EXIT_CODE -ne 0 ]; then
+    #       echo "Pinning failed with exit code $PIN_EXIT_CODE"
     #       cat pin_coq.log
     #       opam list --all-versions coq
     #       exit 1
     #     fi
-    #     stdbuf -oL tee -a pin_coq.log < pin_coq.log
     #     echo "Verifying pin_coq.log..."
     #     ls -l pin_coq.log
     #     cat pin_coq.log
@@ -243,14 +248,15 @@ jobs:
     #     touch install_coq.log
     #     opam install coq.9.0.0 --show-actions | stdbuf -oL tee -a install_coq.log
     #     echo "Installing Rocq 9.0.0..."
-    #     opam install coq.9.0.0 -y --verbose --debug >> install_coq.log 2>&1
-    #     if [ $? -ne 0 ]; then
-    #       echo "Rocq 9.0.0 installation failed"
+    #     opam install coq.9.0.0 -y --verbose --debug > install_coq.log 2>&1
+    #     INSTALL_EXIT_CODE=$?
+    #     stdbuf -oL tee -a install_coq.log < install_coq.log
+    #     if [ $INSTALL_EXIT_CODE -ne 0 ]; then
+    #       echo "Rocq 9.0.0 installation failed with exit code $INSTALL_EXIT_CODE"
     #       cat install_coq.log
     #       opam list --all-versions coq
     #       exit 1
     #     fi
-    #     stdbuf -oL tee -a install_coq.log < install_coq.log
     #     echo "Verifying install_coq.log..."
     #     ls -l install_coq.log
     #     cat install_coq.log
@@ -307,23 +313,24 @@ jobs:
         echo "Installing coq-elpi..."
         eval $(opam env --switch=collatz-proof --set-switch)
         touch install_elpi.log
-        opam install -y --verbose --debug coq-elpi.2.5.2 >> install_elpi.log 2>&1
-        if [ $? -ne 0 ]; then
-          echo "coq-elpi installation failed"
+        opam install -y --verbose --debug coq-elpi.2.5.2 > install_elpi.log 2>&1
+        ELPI_EXIT_CODE=$?
+        stdbuf -oL tee -a install_elpi.log < install_elpi.log
+        if [ $ELPI_EXIT_CODE -ne 0 ]; then
+          echo "coq-elpi installation failed with exit code $ELPI_EXIT_CODE"
           cat install_elpi.log
           exit 1
         fi
-        stdbuf -oL tee -a install_elpi.log < install_elpi.log
         echo "Installing coq-mathcomp-ssreflect..."
         touch install_mathcomp.log
-        opam install -y --verbose --debug coq-mathcomp-ssreflect.2.4.0 >> install_mathcomp.log 2>&1
-        if [ $?
-        -ne 0 ]; then
-          echo "coq-mathcomp-ssreflect installation failed"
+        opam install -y --verbose --debug coq-mathcomp-ssreflect.2.4.0 > install_mathcomp.log 2>&1
+        MATHCOMP_EXIT_CODE=$?
+        stdbuf -oL tee -a install_mathcomp.log < install_mathcomp.log
+        if [ $MATHCOMP_EXIT_CODE -ne 0 ]; then
+          echo "coq-mathcomp-ssreflect installation failed with exit code $MATHCOMP_EXIT_CODE"
           cat install_mathcomp.log
           exit 1
         fi
-        stdbuf -oL tee -a install_mathcomp.log < install_mathcomp.log
         echo "Updating environment..."
         eval $(opam env --switch=collatz-proof --set-switch)
 
