update

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,6 +31,7 @@ jobs:
         opam-repositories: |
           default: https://opam.ocaml.org
           coq-released: https://coq.inria.fr/opam/released
+          coq-core-dev: https://coq.inria.fr/opam/core-dev
 
     - name: Create OPAM Switch and Install Coq
       run: |
@@ -49,16 +50,17 @@ jobs:
 
         echo "Adding and updating OPAM repositories..."
         opam repository add coq-released https://coq.inria.fr/opam/released --all-switches || { echo "Repository add failed"; exit 1; }
+        opam repository add coq-core-dev https://coq.inria.fr/opam/core-dev --all-switches || { echo "Repository add failed"; exit 1; }
         opam update || { echo "OPAM update failed"; exit 1; }
 
         echo "Installing Coq 8.16.1..."
-        opam install -y --verbose coq.8.16.1 || { echo "Coq 8.16.1 installation failed"; exit 1; }
+        opam pin add coq 8.16.1 -y --verbose || { echo "Coq 8.16.1 installation failed"; exit 1; }
 
-        echo "Installing coq-stdlib..."
-        opam install -y --verbose coq-stdlib || { echo "coq-stdlib installation failed"; exit 1; }
+        echo "Installing coq-elpi..."
+        opam install -y --verbose coq-elpi.2.5.2 || { echo "coq-elpi installation failed"; exit 1; }
 
         echo "Installing coq-mathcomp-ssreflect..."
-        opam install -y --verbose coq-mathcomp-ssreflect || { echo "coq-mathcomp-ssreflect installation failed"; exit 1; }
+        opam install -y --verbose coq-mathcomp-ssreflect.2.4.0 || { echo "coq-mathcomp-ssreflect installation failed"; exit 1; }
 
         echo "Verifying Coq installation..."
         if ! opam list --installed | grep -q "coq.*8.16.1"; then
